### ISSUE TITLE
output

### ISSUE THREAD

**Issue by prashantkr2601** [nicholaskajoh/Vehicle-Counting#11]
after all the setup then run the code we found  video processing too slow. how can improve the video processing or video speed rate

**Comment by nicholaskajoh** [comment]
The major bottleneck is vehicle detection. Tracking is also computationally expensive when there are many vehicles in a frame at the same time. Running the algorithms on a GPU dramatically improves the performance. I'm still working on optimizations that will make the algorithms run better on less powerful hardware, but ultimately, high-end hardware would yield much better results.

**Comment by yemikudaisi** [comment]
@nicholaskajoh  how about taking advantage of multiple cores ?

**Comment by nicholaskajoh** [comment]
@yemikudaisi I don't know how multiple cores can be taken advantage of to speed up the system. It would be awesome if there's a way to do that. The vehicle counting process is largely sequential. You have to wait for the next frame to arrive to begin processing and you have to process the current frame fast enough in order to take on the next frame when it arrives. Detection, tracking and counting are sequential as well. You can't track an object you haven't detected or count an object you're not tracking.
