### ISSUE TITLE
I get this error when I clone. Can you please help?

### ISSUE THREAD

**Issue by poornimajoshi** [nicholaskajoh/Vehicle-Counting#19]
(base) PS C:\Users\poorn\Downloads\Vehicle-Counting-master\Vehicle-Counting-master> python Vehicle_Counting.py "./videos
/sample_traffic_scene.mp4"
Traceback (most recent call last):
  File "Vehicle_Counting.py", line 6, in <module>
    from detectors.detector import get_bounding_boxes
  File "C:\Users\poorn\Downloads\Vehicle-Counting-master\Vehicle-Counting-master\detectors\detector.py", line 5, in <module>
    from detectors.tfoda.tfoda_detector import get_bounding_boxes as tfoda_gbb
  File "C:\Users\poorn\Downloads\Vehicle-Counting-master\Vehicle-Counting-master\detectors\tfoda\tfoda_detector.py", line 13, in <module>
    with open(os.getenv('CLASSES_PATH'), 'r') as classes_file:
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by nicholaskajoh** [comment]
Hi  @poornimajoshi! The error is caused by a little bug in _tfoda_detector.py_. I'll fix ASAP. But before then, you can copy the contents of _[.env.example](https://github.com/nicholaskajoh/Vehicle-Counting/blob/master/detectors/tfoda/.env.example)_ to a new file named _.env_ in the same directory (_/detectors/tfoda_) as a temporary fix.

i.e in _/detectors/tfoda/.env_ you should have...
```
WEIGHTS_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/tfoda/faster_rcnn_inception_v2_coco_2018_01_28.pb
CONFIG_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/tfoda/faster_rcnn_inception_v2_coco_2018_01_28.pbtxt
CLASSES_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/tfoda/coco.classes.txt
CLASSES_OF_INTEREST_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/tfoda/coco_interest.classes.txt
CONFIDENCE_THRESHOLD=0.2
```

__PS:__ The contents of the variables don't really matter since you're not using `tfoda` at the moment. But if you choose to do so, you can change them as appropriate.

Cheers!
